site_name: "Documentación HTML"

theme:
  name: material

nav:
  - Inicio: index.md
  - Guía:
      - Quickstart: guia/quickstart.md
      - Etiquetas HTML: guia/etiquetas.md
      - Enlaces HTML: guia/enlaces.md
      - Imágenes HTML: guia/imagenes.md
  - Referencia:
      - Comandos: referencia/comandos.md
      - FAQ: referencia/faq.md